import test, { after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { chromium } from "playwright";

const dataDir = mkdtempSync(join(tmpdir(), "vcb-browser-e2e-"));
process.env.VCB_PORT = "4230";
process.env.VCB_DATA_DIR = dataDir;
const { ensureBoardServer, closeBoardServer } = await import("../src/server.mjs");
await ensureBoardServer();
const base = "http://127.0.0.1:4230";
const json = async path => (await fetch(`${base}${path}`)).json();
const board = await (await fetch(`${base}/api/boards`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ origin: "mcp", toolCallId: "browser-e2e", width: 900, height: 600 }) })).json();
const browser = await chromium.launch({ headless: true, executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1100, height: 850 } });

test("human rich drawing has preview, active mode, movement and UI undo/redo", async () => {
  await page.goto(`${base}/boards/${board.boardId}`);
  await page.getByText("conectado").waitFor();
  const canvas = page.locator("canvas");
  const box = await canvas.boundingBox();
  assert.ok(box);
  assert.equal(await page.locator("#show-grid").isChecked(), true);
  assert.equal(await page.locator("#snap-grid").isChecked(), false);
  const gridVisible = await canvas.evaluate(node => node.toDataURL());
  await page.locator("#show-grid").uncheck();
  const gridHidden = await canvas.evaluate(node => node.toDataURL());
  assert.notEqual(gridVisible, gridHidden);
  assert.equal((await json(`/api/boards/${board.boardId}/state`)).version, 0);
  await page.locator("#show-grid").check();
  assert.equal(await page.locator("#show-drawings").isChecked(), true);
  await page.locator("#show-drawings").uncheck();
  await page.locator("#show-drawings").check();
  await page.locator('[data-create="rectangle"]').click();
  assert.equal(await page.locator('[data-create="rectangle"]').evaluate(node => node.classList.contains("active")), true);
  const start = { x: box.x + 120, y: box.y + 100 };
  await page.mouse.move(start.x, start.y); await page.mouse.down(); await page.mouse.move(start.x + 240, start.y + 150);
  await page.waitForTimeout(80);
  const preview = await canvas.evaluate(node => node.toDataURL());
  assert.notEqual(preview, await page.evaluate(() => { const c = document.querySelector("canvas"); const copy = c.cloneNode(); return copy.toDataURL(); }));
  const beforeCommit = await json(`/api/boards/${board.boardId}/state`);
  assert.equal(beforeCommit.version, 0);
  assert.equal(beforeCommit.elements.length, 0);
  await page.mouse.up();
  await page.waitForFunction(async id => (await fetch(`/api/boards/${id}/state`)).json().then(value => value.version === 1), board.boardId);
  let state = await json(`/api/boards/${board.boardId}/state`);
  assert.equal(state.elements[0].author, "human");
  assert.equal(state.elements[0].type, "rectangle");
  await page.locator("#select-mode").click();
  await page.mouse.move(start.x + 120, start.y + 75); await page.mouse.down(); await page.mouse.move(start.x + 170, start.y + 105); await page.mouse.up();
  await page.waitForFunction(async id => (await fetch(`/api/boards/${id}/state`)).json().then(value => value.version === 2), board.boardId);
  state = await json(`/api/boards/${board.boardId}/state`);
  assert.equal(state.elements[0].x, 170);
  await page.locator("#undo").click();
  await page.waitForFunction(async id => (await fetch(`/api/boards/${id}/state`)).json().then(value => value.version === 1), board.boardId);
  state = await json(`/api/boards/${board.boardId}/state`);
  assert.equal(state.elements[0].x, 120);
  await page.locator("#redo").click();
  await page.waitForFunction(async id => (await fetch(`/api/boards/${id}/state`)).json().then(value => value.version === 2), board.boardId);
  state = await json(`/api/boards/${board.boardId}/state`);
  assert.equal(state.elements[0].x, 170);
  await page.mouse.click(box.x + 220, box.y + 180);
  await page.locator("#delete").click();
  await page.locator("#delete-confirm").click();
  await page.waitForFunction(async id => (await fetch(`/api/boards/${id}/state`)).json().then(value => value.version === 3), board.boardId);
  state = await json(`/api/boards/${board.boardId}/state`);
  assert.equal(state.elements.length, 0);
  const createShape = async (type, startX, startY, endX, endY) => {
    await page.locator(`[data-create="${type}"]`).click();
    assert.equal(await page.locator(`[data-create="${type}"]`).evaluate(node => node.classList.contains("active")), true);
    await page.mouse.move(box.x + startX, box.y + startY); await page.mouse.down(); await page.mouse.move(box.x + endX, box.y + endY); await page.mouse.up();
    await page.waitForTimeout(80);
    return json(`/api/boards/${board.boardId}/state`);
  };
  state = await createShape("ellipse", 100, 350, 260, 470);
  assert.equal(state.elements.at(-1).type, "ellipse");
  state = await createShape("line", 300, 350, 500, 470);
  assert.equal(state.elements.at(-1).type, "line");
  state = await createShape("arrow", 550, 350, 750, 470);
  assert.equal(state.elements.at(-1).type, "arrow");
  page.once("dialog", dialog => dialog.accept("Texto humano"));
  await page.locator('[data-create="text"]').click();
  assert.equal(await page.locator('[data-create="text"]').evaluate(node => node.classList.contains("active")), true);
  await page.mouse.click(box.x + 700, box.y + 100);
  await page.waitForTimeout(80);
  state = await json(`/api/boards/${board.boardId}/state`);
  assert.equal(state.elements.at(-1).type, "text");
  await page.locator("#snap-grid").check();
  await page.locator('[data-create="rectangle"]').click();
  await page.mouse.move(box.x + 73, box.y + 83); await page.mouse.down(); await page.mouse.move(box.x + 181, box.y + 167); await page.mouse.up();
  await page.waitForTimeout(80);
  state = await json(`/api/boards/${board.boardId}/state`);
  const snapped = state.elements.at(-1);
  assert.equal(snapped.x % 24, 0); assert.equal(snapped.y % 24, 0); assert.equal(snapped.width % 24, 0); assert.equal(snapped.height % 24, 0);
  const agentResponse = await fetch(`${base}/api/boards/${board.boardId}/elements`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ origin: "mcp", toolCallId: "agent-grid-freedom", elements: [{ type: "rectangle", x: 73, y: 83, width: 108, height: 84 }] }) });
  assert.equal(agentResponse.status, 201);
  state = await json(`/api/boards/${board.boardId}/state`);
  const agentElement = state.elements.at(-1);
  assert.equal(agentElement.author, "agent"); assert.equal(agentElement.x, 73); assert.equal(agentElement.y, 83);
});

after(async () => { await browser.close(); await closeBoardServer(); rmSync(dataDir, { recursive: true, force: true }); });
